local app_window = require("demo.app.window")

function init(self)
    msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })
    msg.post(".", "acquire_input_focus")

    app_window.resize()
    app_window.center()
end

function on_input(self, action_id, action)
    if action_id == hash("touch") then
        if action.pressed then

        elseif action.released then

        end
    end
end
